version: '3.8'

services:
  next:
    build: .
    container_name: next-app
    volumes:
      - .:/app  # Monte le répertoire courant dans le conteneur
    ports:
      - "3000:3000"  # Expose le port 3000 pour accéder à ton application
    working_dir: /app
    command: yarn dev  # Exécute Next.js en mode développement
    environment:
      - NODE_ENV=development
    tty: true  # Permet une session interactive dans le conteneur (utile pour le debug)
